/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as IkigaiRouteImport } from './routes/ikigai'
import { Route as FabricsRouteImport } from './routes/fabrics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'

const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const IkigaiRoute = IkigaiRouteImport.update({
  id: '/ikigai',
  path: '/ikigai',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricsRoute = FabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/ikigai': typeof IkigaiRoute
  '/mission': typeof MissionRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/ikigai': typeof IkigaiRoute
  '/mission': typeof MissionRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/ikigai': typeof IkigaiRoute
  '/mission': typeof MissionRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fabrics'
    | '/ikigai'
    | '/mission'
    | '/collections/$handle'
    | '/product/$handle'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fabrics'
    | '/ikigai'
    | '/mission'
    | '/collections/$handle'
    | '/product/$handle'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/fabrics'
    | '/ikigai'
    | '/mission'
    | '/collections/$handle'
    | '/product/$handle'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FabricsRoute: typeof FabricsRoute
  IkigaiRoute: typeof IkigaiRoute
  MissionRoute: typeof MissionRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductHandleRoute: typeof ProductHandleRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikigai': {
      id: '/ikigai'
      path: '/ikigai'
      fullPath: '/ikigai'
      preLoaderRoute: typeof IkigaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrics': {
      id: '/fabrics'
      path: '/fabrics'
      fullPath: '/fabrics'
      preLoaderRoute: typeof FabricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FabricsRoute: FabricsRoute,
  IkigaiRoute: IkigaiRoute,
  MissionRoute: MissionRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductHandleRoute: ProductHandleRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
